elasticsearch:
  indexes:
    - name: arvan-cdn
      pattern: "arvan-cdn*"
      schema:
        service_field: "domain"
        status_field: "status"
        time_field: "timestamp"

    - name: prod-nginx
      pattern: "prod-nginx*"
      schema:
        service_field: "host"
        status_field: "status"
        time_field: "@timestamp"

analyze:
  stats_index: "arvan-cdn"
  default_window: "15m"

  default_condition:
    gte: 499
    lt: 600

  excluded_status_codes:
    - 583

  correlation:
      enabled: true

      primary_index: "arvan-cdn"
      secondary_index: "prod-nginx"

      primary_field: "request_id"
      secondary_field: "arvan_request_id"

      max_documents: 10000
      batch_size: 1000